# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c0b24b5aa2a77d8a369d1377572e28dc"
name = "top-cart-test"
handle = "top-cart-test"
application_url = "https://offer-apartment-bridge-uses.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/webhooks/app/uninstalled"

[[webhooks.subscriptions]]
topics = ["app/scopes_update"]
uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://offer-apartment-bridge-uses.trycloudflare.com/auth/callback", "https://offer-apartment-bridge-uses.trycloudflare.com/auth/shopify/callback", "https://offer-apartment-bridge-uses.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
